### ISSUE TITLE
Exception on View Event

### ISSUE THREAD

**Issue by jenniferpiz** [CodepathGroup8-JenniferSonali/LetMeetHappen#23]
To reproduce:
Create A New Event then Click on the newly created event.
-----------------------------
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.skarwa.letmeethappen.models.Location.getName()' on a null object reference
                                                                                      at com.example.skarwa.letmeethappen.activities.ViewEventDetailActivity.generateDetailEventView(ViewEventDetailActivity.java:75)
                                                                                      at com.example.skarwa.letmeethappen.activities.ViewEventDetailActivity.onCreate(ViewEventDetailActivity.java:69)
                                                                                      at android.app.Activity.performCreate(Activity.java:6975)

**Comment by jenniferpiz** [comment]
This only happens if I don't select the location through the map.

**Comment by skarwa10** [comment]
ok will add a check so that location is selected for sure.

**Comment by skarwa10** [comment]
Add Field Validation for New Event Fields.
